### ISSUE TITLE
Request for Hyperparameter Information to Reproduce Results

### ISSUE THREAD

**Issue by ShuheiAsaka** [joonaskalda/PixIT#12]
Hello,

I’m trying to reproduce the results from the paper "PixIT: Joint Training of Speaker Diarization and Speech Separation from Real-world Multi-speaker Recordings" using the code provided in this repository and pyannote. However, I'm unable to match the reported performance.

Specifically, in Table 6 of the paper (λ = 0.5, optimized for DER), the DER is reported as 17.7, while our reproduction experiment yields 22.02.

Could you please share the exact hyperparameters used for training and in the diarization pipeline that led to the reported result? Any additional configuration details that may influence the outcome would also be very helpful.

Thank you in advance!

**Comment by joonaskalda** [comment]
Thank you for your interest and apologies for the delayed response! The likely reason is the diarization pipeline hyperparameters. We optimized the pipeline for DER on the development set. We optimized the segmentation threshold, clustering threshold, and min_cluster_size while freezing asr_collar=0, ending up with the following values: 
```
params:
  segmentation:
    min_duration_off: 0.0
    threshold: 0.5
  clustering:
    method: centroid
    min_cluster_size: 50
    threshold: 0.68
  separation:
    leakage_removal: true
    asr_collar: 0.0
```
